name: FTP Uploader

on:
  push:
    branches: [main]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Sync Files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: "htdocs/"
